name: Generate DMG

on:
  workflow_dispatch:
    inputs:
      macos_version:
        type: choice
        description: "macOS Version"
        required: true
        options:
          - Ventura v13.5.1
          - Monterey v12.7
          - Big Sur v11.7.9
          - Catalina v10.15.7
          - Mojave v10.14.6
          - High Sierra v10.13.6
          - Sonoma Beta v14.0

jobs:
  build-dmg:
    runs-on: macos-latest
    if: github.repository == 'Comp-Labs/Download-macOS'
    steps:
      - uses: actions/checkout@v3

      # MARK: macOS Version

      - if: github.event.inputs.macos_version == 'Ventura v13.5.1'
        name: Download macOS Ventura Latest
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate --fetch-full-installer --full-installer-version 13.5.1

      - if: github.event.inputs.macos_version == 'Monterey v12.7'
        name: Download macOS Monterey Latest
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate --fetch-full-installer --full-installer-version 12.7

      - if: github.event.inputs.macos_version == 'Big Sur v11.7.9'
        name: Download macOS Big Sur Latest
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate --fetch-full-installer --full-installer-version 11.7.9

      - if: github.event.inputs.macos_version == 'Catalina v10.15.7'
        name: Download macOS Catalina Latest
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate --fetch-full-installer --full-installer-version 10.15.7

      - if: github.event.inputs.macos_version == 'Mojave v10.14.6'
        name: Download macOS Mojave Latest
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate --fetch-full-installer --full-installer-version 10.14.6

      - if: github.event.inputs.macos_version == 'High Sierra v10.13.6'
        name: Download macOS High Sierra Latest
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate --fetch-full-installer --full-installer-version 10.13.6

      - if: github.event.inputs.macos_version == 'Sonoma Beta v14.0'
        name: Download macOS Sonoma Beta Latest
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate --fetch-full-installer --full-installer-version 14.0

      # Generate DMG

      # Ventura

      - if: github.event.inputs.macos_version == 'Ventura v13.5.1'
        name: Generate Ventura DMG
        run: |
          sudo hdiutil create -o /tmp/Ventura -size 16384m -volname Ventura -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/Ventura.dmg -noverify -mountpoint /Volumes/Ventura
          sleep 10
          sudo /Applications/Install\ macOS\ Ventura.app/Contents/Resources/createinstallmedia --volume /Volumes/Ventura --nointeraction
          hdiutil eject -force /Volumes/Install\ macOS\ Ventura
          sudo mv /tmp/Ventura.dmg ~/Desktop/Ventura.dmg
      - if: github.event.inputs.macos_version == 'Monterey v12.7'
        name: Upload Ventura DMG
        uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS Ventura
          path: "~/Desktop/Ventura.dmg"

      # Monterey

      - if: github.event.inputs.macos_version == 'Monterey v12.7'
        name: Generate Monterey DMG
        run: |
          sudo hdiutil create -o /tmp/Monterey -size 16384m -volname Monterey -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/Monterey.dmg -noverify -mountpoint /Volumes/Monterey
          sleep 10
          sudo /Applications/Install\ macOS\ Monterey.app/Contents/Resources/createinstallmedia --volume /Volumes/Monterey --nointeraction
          hdiutil eject -force /Volumes/Install\ macOS\ Monterey
          sudo mv /tmp/Monterey.dmg ~/Desktop/Monterey.dmg
      - if: github.event.inputs.macos_version == 'Monterey v12.7'
        name: Upload Monterey DMG
        uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS Monterey
          path: "~/Desktop/Monterey.dmg"

      # Big Sur

      - if: github.event.inputs.macos_version == 'Big Sur v11.7.9'
        name: Generate Big Sur DMG
        run: |
          sudo hdiutil create -o /tmp/BigSur -size 16384m -volname BigSur -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/BigSur.dmg -noverify -mountpoint /Volumes/BigSur
          sleep 10
          sudo /Applications/Install\ macOS\ Big\ Sur.app/Contents/Resources/createinstallmedia --volume /Volumes/BigSur --nointeraction
          hdiutil eject -force /Volumes/Install\ macOS\ Big\ Sur
          sudo mv /tmp/BigSur.dmg ~/Desktop/BigSur.dmg
      - if: github.event.inputs.macos_version == 'Big Sur v11.7.9'
        name: Upload Big Sur DMG
        uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS Big Sur
          path: "~/Desktop/BigSur.dmg"

      # Catalina

      - if: github.event.inputs.macos_version == 'Catalina v10.15.7'
        name: Generate Catalina DMG
        run: |
          sudo hdiutil create -o /tmp/Catalina -size 16384m -volname Catalina -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/Catalina.dmg -noverify -mountpoint /Volumes/Catalina
          sleep 10
          sudo /Applications/Install\ macOS\ Catalina.app/Contents/Resources/createinstallmedia --volume /Volumes/Catalina --nointeraction
          hdiutil eject -force /Volumes/Install\ macOS\ Catalina
          sudo mv /tmp/Catalina.dmg ~/Desktop/Catalina.dmg
      - if: github.event.inputs.macos_version == 'Catalina v10.15.7'
        name: Upload Catalina DMG
        uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS Catalina
          path: "~/Desktop/Catalina.dmg"

      # Mojave

      - if: github.event.inputs.macos_version == 'Mojave v10.14.6'
        name: Generate Mojave DMG
        run: |
          sudo hdiutil create -o /tmp/Mojave -size 16384m -volname Mojave -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/Mojave.dmg -noverify -mountpoint /Volumes/Mojave
          sleep 10
          sudo /Applications/Install\ macOS\ Mojave.app/Contents/Resources/createinstallmedia --volume /Volumes/Mojave --nointeraction
          hdiutil eject -force /Volumes/Install\ macOS\ Mojave
          sudo mv /tmp/Mojave.dmg ~/Desktop/Mojave.dmg
      - if: github.event.inputs.macos_version == 'Mojave v10.14.6'
        name: Upload Mojave DMG
        uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS Mojave
          path: "~/Desktop/Mojave.dmg"

      # High Sierra

      - if: github.event.inputs.macos_version == 'High Sierra v10.13.6'
        name: Generate High Sierra DMG
        run: |
          sudo hdiutil create -o /tmp/HighSierra -size 16384m -volname HighSierra -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/HighSierra.dmg -noverify -mountpoint /Volumes/HighSierra
          sleep 10
          sudo /Applications/Install\ macOS\ High\ Sierra.app/Contents/Resources/createinstallmedia --volume /Volumes/HighSierra --nointeraction
          hdiutil eject -force /Volumes/Install\ macOS\ High\ Sierra
          sudo mv /tmp/HighSierra.dmg ~/Desktop/HighSierra.dmg
      - if: github.event.inputs.macos_version == 'High Sierra v10.13.6'
        name: Upload High Sierra DMG
        uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS High Sierra
          path: "~/Desktop/HighSierra.dmg"

      # Sonoma Beta

      - if: github.event.inputs.macos_version == 'Sonoma Beta v14.0'
        name: Generate Sonoma Beta DMG
        run: |
          sudo hdiutil create -o /tmp/Sonoma -size 16384m -volname Sonoma -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/Sonoma.dmg -noverify -mountpoint /Volumes/Sonoma
          sleep 10
          sudo /Applications/Install\ macOS\ Sonoma\ Beta.app/Contents/Resources/createinstallmedia --volume /Volumes/Sonoma --nointeraction
          hdiutil eject -force /Volumes/Install\ macOS\ Sonoma\ Beta
          sudo mv /tmp/Sonoma.dmg ~/Desktop/Sonoma.dmg
      - if: github.event.inputs.macos_version == 'Sonoma Beta v14.0'
        name: Upload Sonoma Beta DMG
        uses: actions/upload-artifact@v3.1.0
        with:
          name: macOS Sonoma Beta
          path: "~/Desktop/Sonoma.dmg"

  re-run-failed-jobs:
    runs-on: ubuntu-latest
    needs: [build-dmg]
    if: always() && (needs.build-dmg.result == 'failure')
    steps:
      - name: Needs Context
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: |
          echo "$NEEDS_CONTEXT"
